Page({
	data:{
		tabs:[{
			company:"中国能源建设集团华南电力试验研究院有限公司",
			date:"2017-03-15",
			weekDay:"星期三",
			today:"今天",
			time:"16:00",
			university:"华南理工大学",
			location:"五山校区就业指导中心一号报告厅"
		},{
			company:"中国能源建设集团华南电力试验研究院有限公司",
			date:"2017-03-15",
			weekDay:"星期三",
			today:"今天",
			time:"16:00",
			university:"华南理工大学",
			location:"五山校区就业指导中心一号报告厅"
		},{
			company:"中国能源建设集团华南电力试验研究院有限公司",
			date:"2017-03-15",
			weekDay:"星期三",
			today:"今天",
			time:"16:00",
			university:"华南理工大学",
			location:"五山校区就业指导中心一号报告厅"
		},{
			company:"中国能源建设集团华南电力试验研究院有限公司",
			date:"2017-03-15",
			weekDay:"星期三",
			today:"今天",
			time:"16:00",
			university:"华南理工大学",
			location:"五山校区就业指导中心一号报告厅"
		},{
			company:"中国能源建设集团华南电力试验研究院有限公司",
			date:"2017-03-15",
			weekDay:"星期三",
			today:"今天",
			time:"16:00",
			university:"华南理工大学",
			location:"五山校区就业指导中心一号报告厅"
		}]
	}
})